### ISSUE TITLE
Time display

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#10]
Whilst I was doing the manuel (in June 2017), I noticed that my changes on WikiFundi were recorded as modifications made in.... January 2017. So the software was displaying a date out of blue, unrelated to the actual date. This need to be seriously checked.

**Comment by kelson42** [comment]
There is no battery into the R3, so if you unplug it, probably the clock "get lost". Looks like the only way to get that working properly in our case would be to add a GPS receptor (but I have never done this - and this needs of course a new hardware).

**Comment by kelson42** [comment]
I have order a additional hardware clock for the RPI (+20USD per device). Will give it a try.

**Comment by Anthere** [comment]
Any news on this one ?

**Comment by kelson42** [comment]
@rgaudin et moi même avons acheté le hardware et sommes en train de regarder pour le support.

**Comment by rgaudin** [comment]
En cours : https://framagit.org/ideascube/pibox-installer/issues/190

**Comment by kelson42** [comment]
@rgaudin Thx a lot. I close that one as this is basically a duplicate.
