### ISSUE TITLE
[FR] Add Image description templates when uploading pictures on Wikimedia Commons

### ISSUE THREAD

**Issue by kelson42** [openzim/wikifundi#12]
At the moment, users can upload pictures on the wikifundi. However, there is no default template proposed. So users tend to upload the pictures with no information (description, author, source, licence) whatsoever. This really does not convey the right thing to do it. It does not teach them how important it is. And even knowledgeable people will tend not to put anything. Then when pictures are uploaded on Commons… it is a really an issue as the information is not available. We do need to propose a list of licences during the import, even to upload pictures on WikiFundi and we need to propose a default description template.

**Comment by florentk** [comment]
fixed in 0acb683
