### ISSUE TITLE
Category page contains no pages

### ISSUE THREAD

**Issue by florentk** [openzim/wikifundi#27]
The job generates an exception : 

`[exception] [b913e62a7bee69344936bf96] /index.php?title=Special:RunJobs&title=Special%3ARunJobs&tasks=jobs&maxjobs=1&sigexpiry=1528469540&signature=e7d12bae2eb4bc21c741f002f68b4b5ab1c37c9d   Wikimedia\Rdbms\DBUnexpectedError from line 3879 of /var/www/html/includes/libs/rdbms/database/Database.php: DuplicateJob::run: Cannot flush snapshot because writes are pending (JobQueueDB::claimRandom).`

If I lauch the maintenance script `refreshLinks.php`, I have the pages in catagories, but isn't a good solution.

This problem is already appends in MediaWiki previous versions but fixed in release 29 (I use the 31).

**Comment by kelson42** [comment]
@florentk Wouldn't that help to work with MediaWiki 1.30 which is the current stable (instead of a dev branch 1.31)?

**Comment by florentk** [comment]
https://phabricator.wikimedia.org/T196978

**Comment by florentk** [comment]
I'm re-tested, this seem work now, maybe with Nginx configuration ...
