### ISSUE TITLE
Provide solution to export content as tarball

### ISSUE THREAD

**Issue by kelson42** [openzim/wikifundi#32]
As we do not have a solution built-in by Sloopy I see two potential solution:
* Make a small PHP script which would be called online and this script would generate on the fly a tarball
* Write each night a tarball in the data directory (and then we have manually to retrieve it)

**Comment by florentk** [comment]
For the PHP script, this must work : https://secure.php.net/manual/en/function.passthru.php

**Comment by kelson42** [comment]
@florentk If you can catch the compressed stream on the output an "echo" it on the HTTP stream.

**Comment by kelson42** [comment]
@florentk I think we have an answer here https://stackoverflow.com/questions/4357073/lamp-how-to-create-zip-of-large-files-for-the-user-on-the-fly-without-disk-cp

**Comment by florentk** [comment]
fix in 8e4d514

**Comment by kelson42** [comment]
@florentk I reopen the ticket as the logs should not be exported.

**Comment by florentk** [comment]
fix in 9f8d32b
