### ISSUE TITLE
Too many unused filed

### ISSUE THREAD

**Issue by kelson42** [openzim/wikifundi#33]
http://mediawiki.openzim.org/wiki/Special:UnusedFiles... we should really removed them if they are really unused

**Comment by florentk** [comment]
I think that files are really used, counter-example : File:Female_Red-backed_Fairywren_samsonvale.JPG used by Red-backed_fairywren. Just backlinks are not updated (I've not execute completly refreshLink because it's so ... long)

**Comment by kelson42** [comment]
Ok, it is important to provide a coherent instance of mediawiki, even if it takes longer

**Comment by florentk** [comment]
@kelson42 It seem that unused files are now really unused files. I see to reduce this list

**Comment by florentk** [comment]
@kelson42 il y a quand même des problèmes, par exemple Modèle:Infobox_Montagne utilise Fichier:Pic_du_Midi_du_Bigorre.jpg , mais indiqué comme non utilisé

**Comment by florentk** [comment]
@kelson42 il y aussi des doublons
