### ISSUE TITLE
Category to pull-in content has changed

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#39]
In French : [[Catégorie:Projet WikiFundi Contenu]]
In English : [[Category:WikiProject WikiFundi Content]]

**Comment by kelson42** [comment]
@anthere you mean as the replacment of [[Category:Projet_Wikipack_Africa_Contenu]] ?

**Comment by Anthere** [comment]
Last year,
In French: [[Catégorie:Projet Wikipack Africa Contenu]]
In English: [[Category:WikiProject Wikipack Africa Content]]
