### ISSUE TITLE
Report a bug page needs to be updated

### ISSUE THREAD

**Issue by kelson42** [openzim/wikifundi#40]
In http://wikifundi-fr.openzim.org/wiki/WikiFundi:Rapporter_un_bogue

it's not https://github.com/kelson42/wikifundi/ but https://github.com/openzim/wikifundi

**Comment by Anthere** [comment]
To revisit after #39 fixed

**Comment by kelson42** [comment]
@Anthere Still wrong, were are the original pages? are they properly categorized?

**Comment by Anthere** [comment]
Non. Tout va bien. J'ai supprimé cette page dans la nouvelle version pour simplifier.
Le lien vers les débugs sont 
* ici: http://wikifundi-fr.openzim.org/wiki/WikiFundi:À_propos
* là: http://wikifundi-fr.openzim.org/wiki/WikiFundi:Nous_contacter
