### ISSUE TITLE
Retirer la catégorie de pull

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#43]
Note pour ne pas oublier... de retirer

[[Catégorie:Projet WikiFundi Contenu]]

de toutes les pages importées

**Comment by Anthere** [comment]
BUT DO NOT REMOVE that right now. It is useful to debug. This is a reminder that it needs to be done at the end.

**Comment by kelson42** [comment]
@florentk tu peux commenter le bout de code en attendant la fin.

**Comment by florentk** [comment]
@Anthere  @kelson42  l'étape de modificiation des pages (qui supprime, entre autre, la mention de la catégorie) ne sera pas lancée pour le debug, mais dés que j'ai le feu vert, je lancerais cette étape.

**Comment by florentk** [comment]
@florentk ne pas oublier de retirer aussi les sous cagtegories

**Comment by kelson42** [comment]
@florentk Looks like in http://wikifundi-fr.openzim.org/wiki/Cat%C3%A9gorie:Projet_WikiFundi_Contenu
* We still have two pages
* The category page itself is not removed

**Comment by florentk** [comment]
this is fixed, BUT sometime the category page is not updated correctly
