### ISSUE TITLE
Réinsérer les catégories entre balises

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#44]
Par exemple, dans https://fr.wikipedia.org/w/index.php?title=Projet:WikiFundi_Contenu/Île_Antsoheribory&action=edit

Les catégories île et Madagascar doivent être réinsérées

**Comment by kelson42** [comment]
@florentk  See in the original article

```<!--2BREINSERTED
[[Catégorie:Île]]
[[Catégorie:Madagascar]]
-->
```

**Comment by kelson42** [comment]
I still see it here http://wikifundi-fr.openzim.org/w/index.php?title=Lac_Magui&action=edit !

**Comment by florentk** [comment]
fix in  225a433 , this will appears in next mirroring
