### ISSUE TITLE
Image import

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#45]
Some images seem to have been imported. 
Many are missing. 
Example : http://wikifundi-fr.openzim.org/wiki/Les_fêtes_en_Tunisie
http://wikifundi-fr.openzim.org/wiki/Île_Antsoheribory
http://wikifundi-fr.openzim.org/wiki/Musée_de_Guellala
http://wikifundi-fr.openzim.org/wiki/Jeux_populaires_sahariens
http://wikifundi-fr.openzim.org/wiki/Fort_de_Médine
http://wikifundi-fr.openzim.org/wiki/Lac_Magui

**Comment by florentk** [comment]
@kelson42 @Anthere  This files were imported last night (this are files > 5Mb), but thumbail can not generate (volume full ?)

**Comment by Anthere** [comment]
I fear that is correct. I just tried to create an account and got this error

MediaWiki internal error.

Original exception: [156e38087a70e0268c85be95] /w/index.php?title=Sp%C3%A9cial:Cr%C3%A9er_un_compte&returnto=Accueil Wikimedia\Rdbms\DBQueryError from line 1457 of /var/www/html/w/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: INSERT OR IGNORE INTO user (user_name,user_password,user_newpassword,user_email,user_email_authenticated,user_real_name,user_token,user_registration,user_editcount,user_touched) VALUES ('Anthere','','','',NULL,'','baf294ca7a45ce37e649ad38ec348cb7','20180625105018','0','20180625105023')
Function: User::addToDatabase/single-row
Error: 13 database or disk is full

**Comment by Anthere** [comment]
This said... whilst I was looking for pages where the word "bug" might be... I found out that there is a whole bunch of articles in the database that simply should not be there. Look at http://wikifundi-fr.openzim.org/w/index.php?search=bug&title=Spécial%3ARecherche&go=Continuer

I think many articles were imported when they should not be... which could explain the full disk....

Check out : http://wikifundi-fr.openzim.org/wiki/Spécial:Toutes_les_pages

**Comment by florentk** [comment]
@Anthere J'ai vérifié, il y a juste le fichier "Jeu de chèche.webm" qui n'a pas été Téléversé car > 100 Mb (nouvelle limite). Sur tout le site, ça concerne 7 vidéos.

**Comment by Anthere** [comment]
Pourrais tu me dire quels sont les 7 vidéos qui ne s'importent pas ?

**Comment by kelson42** [comment]
@Anthere Do we really need to migrate them?
