### ISSUE TITLE
Some pages should not be there...

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#46]
Either they have been deleted from our new version. 
Example : 
http://wikifundi-fr.openzim.org/wiki/WikiFundi:Wikipack_Africa

It is as if the system has kept the pages that existed in V1. It did not update them since they do not exist in V2. But they simply should not be there. 

*************

Or they exist both under the real title and under the currently one wikipedia title.
Example:
http://wikifundi-fr.openzim.org/wiki/Projet:Wikipack_Africa_Contenu/WikiFundi:Wikipack_Africa
http://wikifundi-fr.openzim.org/wiki/Projet:Wikipack_Africa_Contenu/WikiFundi:Bienvenue
http://wikifundi-fr.openzim.org/wiki/Projet:Wikipack_Africa_Contenu/Aide:Projets_pédagogiques

Are pages that already exist as 
http://wikifundi-fr.openzim.org/wiki/WikiFundi:Bienvenue

**Comment by kelson42** [comment]
@florentk I let you explain the content update strategy/schedule (i think we need a full refresh here to fix the pb).

**Comment by florentk** [comment]
this will be fixed after a full mirroring
