### ISSUE TITLE
Links at the bottom of the software

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#48]
Those links currently are
Politique de confidentialité À propos de WikiFundi Avertissements Version mobile

They should be
Projet:WikiFundi Contenu/WikiFundi:À propos
Projet:WikiFundi Contenu/WikiFundi:Avertissements généraux
Projet:WikiFundi Contenu/WikiFundi:Nous contacter
Projet:WikiFundi Contenu/WikiFundi:Crédits
Version mobile

I remember that last year, I had to tweak something directly on the host wiki to make that work. But I do not remember what...
Any pointer would be welcome. Kelson, do you remember which page on MediaWiki explained how to do that ? 

This is not urgent, but needs to be done before the final export

**Comment by florentk** [comment]
@kelson42 I follow the instructions in this page https://www.mediawiki.org/wiki/Manual%3aFooter#Add_links_to_the_footer

but this seem not work to add a new item. To test,  I had add this code into LocalSetting.custom.php:
`$wgHooks['SkinTemplateOutputPageBeforeExec'][] = function( $sk, &$tpl ) {
	$tpl->set( 'termsofuse', $sk->footerLink( 'termsofuse', 'termsofusepage' ) );
	$tpl->data['footerlinks']['places'][] = 'termsofuse';
	return true;
};`

**Comment by florentk** [comment]
@Anthere for existing links you can modify title and url, as explained here : https://www.mediawiki.org/wiki/Manual%3aFooter#Customizing_the_Built-in_items

And I will add two not existing link:
- Credit 
- Contact
As exsting link, to activate and custom this new links, you must create four pages : MediaWiki:Credit, MediaWiki:Creditpage, MediaWiki:Contact and MediaWiki:Contactpage

**Comment by florentk** [comment]
fixed in f9e8a06

**Comment by Anthere** [comment]
https://fr.wikipedia.org/wiki/Projet:WikiFundi/Contenu#Liens_du_bas
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_WikiFundi_Content#Bottom_menu_links

**Comment by kelson42** [comment]
This was a problem during the integration, not with WikiFundi itself.
