### ISSUE TITLE
The text in a subcategory was not transferred

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#53]
I noted this category appeared in red
http://wikifundi-fr.openzim.org/wiki/Catégorie:Pour_en_savoir_plus_sur_WikiFundi
There is no description text.

Whilst the original category on wikipedia did contain text. 
https://fr.wikipedia.org/w/index.php?title=Catégorie:Pour_en_savoir_plus_sur_WikiFundi&oldid=149743997

Pages listed within the category are fine. That's the description within the category that is missing.

**Comment by florentk** [comment]
fixed in 5c1ecbb
