### ISSUE TITLE
Set up of an admin account on the wiki

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#57]
It should be as is

Les​ ​identifiants​ ​du​ ​compte​ ​administrateur​ ​sont 
Nom​ ​utilisateur​ ​:​ ​​admin
Mot​ ​de​ ​passe​ ​:​ ​​adminadmin

**Comment by Anthere** [comment]
Note, obviously, there is an admin account. However, the password is not the one defined last year (and currently distributed in user guide). We better stick to exactly the same password to avoid running into problems
http://wikifundi-fr.openzim.org/wiki/Spécial:Liste_des_utilisateurs

**Comment by florentk** [comment]
Ok actuellement le compte administrateur est
Nom d'utilisateur : Admin
Mot de passe : wikiadmin
Je vais le modifier pour que se soit admin / adminadmin

**Comment by florentk** [comment]
fixed in bfff468
