### ISSUE TITLE
Unable to reuse imported media

### ISSUE THREAD

**Issue by rgaudin** [openzim/wikifundi#58]
When editing a page using the Visual Editor, one should be able to __Insert__ > __Media__ and reuse any image already present (either from the initial data or later uploads).

At the moment, the media browser can't find any media.

__Test__ with `Cinderella` string for example which should trigger [Fichier:Cinderella_-_Project_Gutenberg_etext_19993.jpg](http://wikifundi-fr.openzim.org/wiki/Fichier:Cinderella_-_Project_Gutenberg_etext_19993.jpg).

Note that using any media (initial or new) using Wikicode works fine.

Affects both wikifundi 1 and 2.

**Comment by rgaudin** [comment]
Hey,
It is apparently a performance issue. It works fine on real hardware.
I'll leave it up to you to close this issue or not 😉

**Comment by kelson42** [comment]
OK, I close the ticket for now. Thx for reporting the ticket @rgaudin
