### ISSUE TITLE
An OGV video has not been migrated properly

### ISSUE THREAD

**Issue by kelson42** [openzim/wikifundi#60]
At http://wikifundi-en.openzim.org/wiki/Help:How_to_edit_a_page#Creating_a_Wikipedia_article

**Comment by florentk** [comment]
the size of this video is 42.51 MB, I have limited file to 20 MB. I do not know which size to choose as the limit to avoid overloading the archive or exceeding the volume quota. Several files are very heavy  : 

`
[https://upload.wikimedia.org/wikipedia/commons/8/8b/Barack_Obama_inaugural_address.ogv] (418.23 MB)
[https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/NGC_3372a-full.jpg/1024px-NGC_3372a-full.jpg] (200.06 MB)
[https://upload.wikimedia.org/wikipedia/commons/a/ae/Open_Letter_for_Free_Access_to_Wikipedia_%28EN_subtitles%29.webm] (104.31 MB)
[https://upload.wikimedia.org/wikipedia/commons/8/87/Lion_tamer_LCCN94507637.tif] (230.01 MB)
[https://upload.wikimedia.org/wikipedia/commons/e/ee/Open_Letter_for_Free_Access_to_Wikipedia.webm] (101.12 MB)
[https://upload.wikimedia.org/wikipedia/commons/8/8e/New_Horizons_Extreme_Close-Up_Of_Pluto_Surface_%28No_Audio%29.ogv] (514.22 MB)

`

**Comment by florentk** [comment]
je vais relancer la migration avec une limite à 100 Mo pour voir, du coup les fichiers non copiés seront ceux listés ci-dessus.

**Comment by Anthere** [comment]
Out of those above, the only I really care about is 
[https://upload.wikimedia.org/wikipedia/commons/a/ae/Open_Letter_for_Free_Access_to_Wikipedia_%28EN_subtitles%29.webm] (104.31 MB)

I see why the Lion one is here. I am going to deactivate it from the article page. I dunno why the others are here yet.
