### ISSUE TITLE
Pdf still not displayed

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#61]
http://wikifundi-fr.openzim.org/wiki/WikiFundi:Premiers_pas

The image on the right should be a pdf. The message I see is "Erreur lors de la création de la miniature : libgomp: Thread creation failed: Resource temporarily unavailable"

**Comment by florentk** [comment]
@Anthere This works now, I think that is a transicent problem, I looking for avoid this.

**Comment by florentk** [comment]
fix in 97a85bb

**Comment by florentk** [comment]
this bug persists, I investigate

**Comment by florentk** [comment]
@Anthere this seem as a memory ressource probleme, to get around this problem, we can change thumb size (200px)

**Comment by florentk** [comment]
@rgaudin what does it look on a raspberry ?

**Comment by rgaudin** [comment]
@florentk I didn't had time to test on a Pi yet. Do you still want the test? Will be able to do it in the next couple days I think.
