### ISSUE TITLE
some articles should not be displayed

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#62]
For example, there is a whole collection such as 
http://wikifundi-fr.openzim.org/wiki/2017/GT/1.2/D/10a
Should not be there...

**Comment by Anthere** [comment]
See in here : http://wikifundi-fr.openzim.org/wiki/Spécial:Toutes_les_pages

**Comment by Anthere** [comment]
Still are some articles that should not be there....

**Comment by florentk** [comment]
@Anthere yes this seem be dependencies of page files and the namespace change during mirroring, I investigating this bug

**Comment by florentk** [comment]
fix in 6e2031f for majority of articles, but on FR I thinks few articles should not be displayed : 
- 2018/Modèle LP
- 7 juillet
- 7 juillet 2018
- Juillet 2018

**Comment by florentk** [comment]
fix in 67d759c
