### ISSUE TITLE
Gostscript errror  (core dumped) on some thumbnails from PDF

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#64]
In this page (scroll down), a couple of images miniatures are missing.
http://wikifundi-fr.openzim.org/wiki/WikiFundi:Ressources

I looked if the images were there. Apparently they are missing.

**Comment by florentk** [comment]
@Anthere this files are not missing, this is an thumb creation issue

**Comment by Anthere** [comment]
Ok... I looked for one example.
Here it is : http://wikifundi-fr.openzim.org/wiki/Spécial:Liste_des_fichiers?limit=50&ilsearch=WLA+PhotoComp2016+Pull+Up+banner.pdf&user=

**Comment by florentk** [comment]
Error : `'/usr/bin/convert' (core dumped)`
Concern 3 files on Ressource page :
WLA_Pull_up_banner_RT_CMYK_PF.pdf
WLA_PhotoComp2016_Pull_Up_banner.pdf
WikiLovesAfrica_generic_pull_Up_banner_PF_FA.pdf

**Comment by florentk** [comment]
similar bug https://www.mediawiki.org/wiki/Topic:Uaj2hidtvh9xjokc

**Comment by Anthere** [comment]
Is there a technical solution or should I remove those three images ?

**Comment by kelson42** [comment]
@florentk What happens if you start the command line by hand?

**Comment by kelson42** [comment]
@florentk J'ai lancé la commande à la main sur le docker et cela marche en 20s... donc y'a un pb quelconque au niveau de la conf de MW.

**Comment by kelson42** [comment]
@florentk I would recommend to have a look in details to that page https://www.mediawiki.org/wiki/Manual:$wgMaxShellMemory

**Comment by florentk** [comment]
@kelson42 j'ai augmenté cette valeur en local à 512Mo, ça ne change rien  :(

**Comment by kelson42** [comment]
@florentk peut-etre que tu as besoin de plus... en tout cas la machine et le software fonctionnent.

**Comment by florentk** [comment]
@kelson42 I fixed this bug ! I set `$wgMaxShellFileSize` at 512 Mo, maybe a big temp file is used

**Comment by Anthere** [comment]
Awesome !

**Comment by kelson42** [comment]
http://wikifundi-en.openzim.org/wiki/File:What_is_Wikipedia_Zero%3F.webm thumbnail is not OK (probably for a similar reason).

**Comment by florentk** [comment]
@kelson42  Is not for a similar reason, this seem be a bug of Convert caused by a special char ('?') . I see a similar report here : https://stackoverflow.com/questions/23684903/imagemagick-error-unable-to-open-image

**Comment by florentk** [comment]
I tryed on my system (without Docker), I have the same bug  :  
`
florent@pc:/var/opt/volumes/wikifundi/data-en/images/e/e4$ convert -quality 80 -background white -define 'jpeg:size=300x169' '/var/opt/volumes/wikifundi/data-en/images/thumb/e/e4/What_is_Wikipedia_Zero\?.webm/1920px-seek=52-What_is_Wikipedia_Zero\?.webm.jpg' -thumbnail '300x169!' +set 'Thumb::URI' -depth 8 -sharpen '0x0.4' -rotate '-0' -sampling-factor '2x2,1x1,1x1' '/tmp/transform_d96f014f3964.jpg'
convert: impossible d'ouvrir l'image `/var/opt/volumes/wikifundi/data-en/images/thumb/e/e4/What_is_Wikipedia_Zero\?.webm/1920px-seek=52-What_is_Wikipedia_Zero\?.webm.jpg': Aucun fichier ou dossier de ce type @ error/blob.c/OpenBlob/2712.
convert: pas d'images définies `/tmp/transform_d96f014f3964.jpg' @ error/convert.c/ConvertImageCommand/3210.

florent@pc:/var/opt/volumes/wikifundi/data-en/images/e/e4$ ls /var/opt/volumes/wikifundi/data-en/images/thumb/e/e4/What_is_Wikipedia_Zero\?.webm/1920px-seek=52-What_is_Wikipedia_Zero\?.webm.jpg
/var/opt/volumes/wikifundi/data-en/images/thumb/e/e4/What_is_Wikipedia_Zero?.webm/1920px-seek=52-What_is_Wikipedia_Zero?.webm.jpg
florent@fixie:/var/opt/volumes/wikifundi/data-en/images/e/e4$ 


`

**Comment by kelson42** [comment]
@florentk thank you for the investigation. Then we have an other reason to fix that bug I have open yesterday https://github.com/openzim/wikifundi/issues/72
