### ISSUE TITLE
504 Gateway Time-out at 30s on Sloppy

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#65]
Happens each time I try to create an article, or search

---> could not test article creation

**Comment by florentk** [comment]
@Anthere yes I got this many time on first time to consult page (or first time article creation), I update page to get around.

**Comment by florentk** [comment]
@kelson42  I looking for increase the timeout in Nginx config

**Comment by Anthere** [comment]
Well. I could not do the videos because of that... :(

**Comment by florentk** [comment]
@Anthere @kelson42  ok, this is troublesome. Even by increasing timeout, the display may be long because we have resources problems

**Comment by kelson42** [comment]
@florentk I do not know what exactly is mean with "create an article", but it has worked the last weeks and this is not a costly operation. I suspect something else is wrong.

**Comment by florentk** [comment]
@kelson42 yes, but I just tested, we had no problem now, the creation page is quickly for me. But the first time after mirroring, I think this operation is really costly without the cache.

**Comment by florentk** [comment]
@kelson42 Or when I consult for the first time an page just before and I falls on a Gateway timeout, jobs to create multiples thumbs while porcessing, this can slow the creation page and got a Gateway timeout. I already got it.

**Comment by florentk** [comment]
I can see to generate all thumb after mirroring, this operation is possible with the retricted number of article now

**Comment by Anthere** [comment]
yes. Ok. I'll check that after the next mirroring

**Comment by florentk** [comment]
fix in https://github.com/openzim/mediawiki-docker/commit/c22c0afe8065743e1f1e75fd78e31ad3caffed66

**Comment by florentk** [comment]
the most of page load more quickly with pre-generated thumbs, but for big page (like ressource), the timout happend. I configurerd Nginx with timeout at 600 s, but this seem no enough, did I miss something

**Comment by kelson42** [comment]
@florentk The problem is IMO not the timeout on HTTP, the pb is the timeout to generate the thumbnail.

**Comment by kelson42** [comment]
@Anthere I tried to create articles and it works (even if the first attempt something went wrong). I also tried on the Kiwix-plug online demo and it works too. Tested with Firefox.

**Comment by Anthere** [comment]
in spite of trying many times, ogv and webm do not get uploaded

**Comment by kelson42** [comment]
@Anthere Always the same problem (timeout after 30s)? Otherwise there is a limitation on 5MB, so I guess you are over the limit?

**Comment by Anthere** [comment]
Certainly over 5MB limit. But some files (mpeg) uploaded just fine and are also above 5 MB

**Comment by Anthere** [comment]
But this said... I wonder if we may not talk of two different things... I am talking of the edupi dashboard and uploading WikiFundi resources. Are we talking of the same thing ?

**Comment by kelson42** [comment]
@Anthere OK, then this has nothing to do here. This is an other topic... and quite sure this is a problem with Safari (as I have tested all these cases with both Firefox and Chrome) ... something we can not do anything against :(
