### ISSUE TITLE
Bad links on Wikipedia:xxx

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#66]
See here for example in the "Showcase of good Wikipedia articles" paragraph

http://wikifundi-en.openzim.org/wiki/WikiFundi:Welcome

When there are pages that start with "Wikipedia:blabla", instead of heading to the proper wikifundi page, they are redirected to Wikipedia itself.  As a result, many links are wrong in that page

**Comment by florentk** [comment]
@Anthere ok, I resolve it by replace I link Wikipedia:blabla by Wikifundi;blabla. I am looking to modify these links during the mirroring

**Comment by Anthere** [comment]
Hmmm. But the problem is that we have different spaces on WikiFundi at the moment. Amongst those one is WikiFundi:blabla and another is Wikipedia:blabla and we do not host the same things in both spaces...

**Comment by florentk** [comment]
@Anthere j'essaye de comprendre, sur la [page original](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_WikiFundi_Content/WikiFundi:Welcome) ces liens pointent vers des pages qui n'existent pas. Quand je les importe, elle doivent pointer dans vers _namespace_ ? Est-ce que la page de destination est quand même bien importée ou pas ?

**Comment by Anthere** [comment]
So let's pick up an exemple. 
Original context : https://en.wikipedia.org/wiki/Wikipedia:WikiProject_WikiFundi_Content/WikiFundi:Welcome
Target context: http://wikifundi-en.openzim.org/wiki/WikiFundi:Welcome
Check out : Under Showcase of good Wikipedia articles
Original page : https://en.wikipedia.org/wiki/Wikipedia:WikiProject_WikiFundi_Content/Wikipedia:Showcase
After scraping of first part of the url, target page should become "Wikipedia:Showcase"
Right now, clicking on the link forward us directly to the REAL online Wikipedia:Showcase page. 
When I search for "Wikipedia:Showcase" on WikiFundi, I get this : http://wikifundi-en.openzim.org/wiki/Special:GoToInterwiki/wikipedia:Showcase

So I look into http://wikifundi-en.openzim.org/wiki/Special:AllPages to try to see if that page exist somewhere. And I think I get the problem... when in Special:AllPages, if you check out the list of spaces available, you will notice that there is a "Wikipédia" namespace. The namespace on the English WikiFundi should be a "Wikipedia" namespace.

**Comment by florentk** [comment]
@Anthere  Thanks for the debug, I find the bug in MediaWiki config, I had configured "Wikipédia" namespace in the EN version, the update is in progress....

**Comment by Anthere** [comment]
I am unsure whether this bug is supposed to be fixed now or not. 
However, what I see is that it is not working at all. The Wikipedia:xxx has now been replaced by WikiFundi:xxx
Which does not solve the problem at all. All the links between articles are as Wikipedia:xxx. So having WikiFundi:xxx as name of the articles is breaking all the links. 

Two interesting links to second that
* http://wikifundi-en.openzim.org/wiki/Category:About_Wikipedia_on_WikiFundi
* https://en.wikipedia.org/wiki/Category:About_Wikipedia_on_WikiFundi

**Comment by florentk** [comment]
@Anthere In fact, I have not lauch a full mirroring, this problem will be fixed after a full mirroring

**Comment by florentk** [comment]
fix in last mirroring for FR and EN
