### ISSUE TITLE
Lua error : attempt to index field 'wikibase' (a nil value).

### ISSUE THREAD

**Issue by florentk** [openzim/wikifundi#67]
append when page use a Module with this instrcution  : `mw.wikibase.getEntity(val)`
Ex : http://wikifundi-fr.openzim.org/wiki/%C3%89cole_des_arts_industriels_et_des_mines

@kelson42 any idea to solve this without install wikibase extension (we remove it because the search box doesn't work)

**Comment by kelson42** [comment]
@florentk You need to tweak the piece of Lua to return empty string or similar.

**Comment by florentk** [comment]
@kelson42 ok, I thinks remplace `mw.wikibase.getEntity(val)` by `nil` in all module

**Comment by florentk** [comment]
fix in e7a9131
