### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#69]
On the French WikiFundi, main page results in this : http://wikifundi-fr.openzim.org/wiki/Main_Page
It is not a bug. Just weird. Taking a note right now to figure out whether it is a problem or not later. 
Nothing to do

**Comment by Anthere** [comment]
Also note
http://wikifundi-fr.openzim.org/wiki/Projet:Modèle/Modèles

Not sure why it is there. No big deal though...

**Comment by Anthere** [comment]
This one should not be there. I could delete it manually at the last minute
http://wikifundi-fr.openzim.org/wiki/Projet:Protection_du_patrimoine/image

**Comment by florentk** [comment]
@Anthere , If needed,  I can see to create a list of pages to delete after mirroring

**Comment by florentk** [comment]
For "Projet" page, I will add the extra namespace "Projet" to not show these pages in the Main namespace. 
For "Main Page", it is in the initial database, I can delete after mirroring.

**Comment by Anthere** [comment]
ok

**Comment by florentk** [comment]
fixed in 8b00093
