### ISSUE TITLE
Inadequate render on small screens:1

### ISSUE THREAD

**Issue by michaelgraaf** [openzim/wikifundi#7]
In "broadcasting" WF to a group, some users, on seeing the top button only (when the layout of the button box has been made vertical on their phones) do not realise there are any other buttons below. On re-creating this on a Samsung Android at home, part of the button below is visible. This was not always the case in the group.

Solution would be to let the buttons (and box) shrink and remain in landscape, so that the users are prompted to hold the phone horizontally (once they see the box is too wide for the screen)

![20170427_061112](https://cloud.githubusercontent.com/assets/28103242/25486647/29f2f036-2b62-11e7-946f-08d860cdfb54.jpg)
![2017-04-27 06 10 21](https://cloud.githubusercontent.com/assets/28103242/25486791/8b632d68-2b62-11e7-836c-b22ff9f7eb37.jpg)

.

**Comment by kelson42** [comment]
Thx for the report, maybe @Anthere can do something, I do not have developed that page.

**Comment by Anthere** [comment]
I did not develop that page ... actually, I think you did Emmanuel, but upon guidance from the designer (for the visual). But the practical model of it came from an idea from you, probably inspired from another similar project ?
Well, it does not matter who has the responsibility for the outcome. What matters is that this page does not work well...
Thank you so much for the screenshots, that is VERY helpful feedback Michael.

So this is added to the list of "can be fixed and must be fixed" for the next version! Thank !

Flo
