### ISSUE TITLE
Resources that will not get uploaded

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#73]
CAN NOT BE UPLOADED
This_is_Wikipedia.webm.webm
I guess because it is 80 MB. (in Wikimedia Videos)
https://www.dropbox.com/s/kjnnpyf5soqk6pt/This_is_Wikipedia.webm?dl=0

DONE 
_Nor did WikiFundi Set Up Video English.mp4
96 MB (in WikiFundi pack)
I got back a lighter 20MB version
https://www.dropbox.com/s/s2afhkd01ud5sj7/WikiFundi%20Set%20Up%20Video%20in%20English%2020MB.mp4?dl=0_

CAN NOT BE UPLOADED
Nor BeFearlessFramework_Nov15.pdf
5,1 MB (in Wikipedia Ressources English)
https://www.dropbox.com/s/zejz9v692pmxdul/BeFearlessFramework_Nov15.pdf?dl=0

CAN NOT BE UPLOADED
Brochure_Wikipédia_enseignants-chercheurs_"Utiliser_Wikipédia_avec_vos_étudiants_-_Études_de_cas"
1.7 MB (in Wikipedia Ressources Francais)
https://www.dropbox.com/s/bemoujc9610fuyh/Brochure_Wikip%C3%A9dia_enseignants-chercheurs_%22Utiliser_Wikip%C3%A9dia_avec_vos_%C3%A9tudiants_-_%C3%89tudes_de_cas%22.pdf?dl=0

Guide_Photographique_Wiki_Loves_Africa_(Format_impression)
Guide_Photographique_Wiki_Loves_Africa_(Format_web)
 (in Wikipedia Ressources Francais)
https://www.dropbox.com/s/5ckxhlazp7xuxjr/Guide_Photographique_Wiki_Loves_Africa_%28Format_impression%29.pdf?dl=0
https://www.dropbox.com/s/4elb7vdx74t72fm/Guide_Photographique_Wiki_Loves_Africa_%28Format_web%29.pdf?dl=0

Wikipédia_en_classe
32 MB (in Wikipedia Ressources Francais)
https://www.dropbox.com/s/yg9c6e00xgrbmco/Wikip%C3%A9dia_en_classe.pdf?dl=0

**Comment by kelson42** [comment]
@Anthere Tu parles des resources sur le plug?

**Comment by Anthere** [comment]
yes. Edupi. Those last ones did not want to get in, no matter what I tried. It is a problem. What do you suggest ?

**Comment by kelson42** [comment]
Je confirme que je n'arrive pas non plus à uploader https://www.dropbox.com/s/kjnnpyf5soqk6pt/This_is_Wikipedia.webm?dl=0 sur http://edupi.edupi-fr.demo.plug.kiwix.org. @rgaudin une idée?

**Comment by rgaudin** [comment]
C'est à dire ? Il y a un message d'erreur ou autre ?

Ça ne semble pas être lié au format `webm` en particulier ; je viens d'uploader [celui-la](http://dl3.webmfiles.org/big-buck-bunny_trailer.webm) dans le [dossier renaud](http://edupi.edupi-fr.demo.plug.kiwix.org/#directories/1)

**Comment by Anthere** [comment]
C'est à dire qu'après des temps immémoriaux (j'ai une connection catastrophique, d'ailleurs je crains le téléchargement de l'image finale...), le petit visuel obtenu est une croix et non une coche. Et le fichier n'apparait pas. C'est tout (pas de message d'erreur)

**Comment by rgaudin** [comment]
OK, @kelson42 tu peux faire le test, toi qui a une connexion rapide ?

En général, quand il y a une erreur, on voit le message en passant la souris sur la croix, ça apparait dans une bulle. En tout cas, c'était le cas pour le problème de taille.

**Comment by kelson42** [comment]
@rgaudin J'avais deja pas mal testé et tout sembler finalement marcher correctement (en plus j'ai oublié le mot de passe en cours sur le site de mo). Est-ce que tu peux simplement t'assurrer stp que les fichiers sont dans les ZIP de ressources pour Wikifundi Edupi?

**Comment by rgaudin** [comment]
Ok je vérifierai que c’est à jour.

**Comment by rgaudin** [comment]
Updated the ZIP file with minor changes:

* removed one file that was duplicated
* Added one missing file

Updated presets as well.
