### ISSUE TITLE
Autodisplay

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#76]
After connecting to WikiFundi network, there is no "captive window" or auto-display system. When opening a browser, the user either
* gets a message telling him that this network is not secured. Then does not know what to do
* typing anything in the browser may lead him to wikifundi.lan. 
Sometimes.
* or nothing happens at all, and the user has no idea what he should do next. 

For example, on Firefox, the message I got is

"Se connecter au réseau

Ce réseau nécessite que vous vous connectiez à un compte pour utiliser Internet.
Ce site a recours à HTTP Strict Transport Security (HSTS) pour indiquer à Firefox de n’établir qu’une connexion sécurisée. Ainsi il n’est pas possible d’ajouter d’exception pour ce certificat."

On Chrome, it says 

"Connexion au réseau Wi-Fi
Pour utiliser ce réseau Wi-Fi (WikiFundi), il est possible que vous deviez vous rendre sur la page wikifundi.lan."

Which at least gives the idea that people should try to type wikifundi.lan in their browser. 

Except that when they do... sometimes nothing happens. 

The proper url seems to be wikifundi.lan/fr or wikifundi.lan/en or wikifundi.lan

I have no idea if this can be fixed. 

Talking with James from WikiMed, he told me that the best solution would be a "captive window". 

At a minimum, please add to the description to install wikifundi the proper steps they have to do to actually access the tool.

But we have a big issue here as it becomes too complicated for a user who can not ask for help. 

The best example here is that when I presented WikiFundi at Wikimania, only one person wrote something on it. I suppose most of the others did not manage to access it. I am curious what will be the feedback from the UserGroup or Michael on that issue.

**Comment by kelson42** [comment]
@rgaudin This is a ticket for kiwix-plug

**Comment by rgaudin** [comment]
Yes, it's not specific to WikiFundi. I opened [an issue there](https://framagit.org/ideascube/pibox-installer/issues/193). Comments welcome.

Closing this one as duplicate.
