### ISSUE TITLE
Connexion button on the welcome screen

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#77]
For some reasons, there is a "connexion" button top right. It actually seems to be the system that make it possible to access the edupi admin (I noticed it works with the regular admin password) Now, for the regular user, this is utterly confusing. Already several people asked me "what is the login to access the tool" because they first try to login and naturally have no idea what to put it here. 

This login button needs to go away. If not, it needs to be very small and more explicit such as "connexion to edupi environnement" so that users do not believe they have to log in there. But honestly, it is super confusing and I would prefer it to simply go away.

**Comment by kelson42** [comment]
@Anthere I might be able to blind it.

**Comment by rgaudin** [comment]
OK, hidden in CSS.
