### ISSUE TITLE
 Inside the Edupi resources application

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#78]
The yellow button allowing to access the resources is "Resources" (for English and French)

Change it to "WikiFundi resources" in English

And "Ressources WikiFundi" in French

If only one language is possible at this stage, keep English as default.

**Comment by kelson42** [comment]
@rgaudin Can you change this?

**Comment by rgaudin** [comment]
I think it’s obsolete and that we are now greated with the
language-specific buttons directly.

**Comment by kelson42** [comment]
@rgaudin OK, will verify it.

**Comment by rgaudin** [comment]
Verified.
