### ISSUE TITLE
Credits on welcome screen

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#79]
![screenshot credits v1](https://user-images.githubusercontent.com/19579170/43358203-0c56bc76-928e-11e8-9f83-e00bc32ea30f.jpeg)
We need a credit text on the main entrance page. I do not know where it can fit technically. Either in the white space below the tool access; Or in the blue area. 

Our tool was credited as such last year. See screenshot: 

The top (more information blabla)) : no change

The logos: remove WikiAfrica logo. Add Wiki in Africa, Wikimedia Foundation, and Kiwix logo
Wiki in Africa logo should be the first on the line.

The WiA logo: https://commons.wikimedia.org/wiki/File:WIA-LOGO_colour.png

Text should be changed as such : 

WikiFundi is a Wiki in Africa project in support of Wikipedia. The plateform is created by Florence Devouard and Isla Haddow-Flood to support the WikiAfrica mouvement. It is realized in collaboration with Kiwix. It is funded by the Orange Foundation and the Wikimedia Foundation. WikiFundi and its documentation is licensed under CC-BY-SA 4.0

**Comment by kelson42** [comment]
@Anthere I will try to do so, we would need a translated version in French I think!? Can you provide it?

**Comment by Anthere** [comment]
WikiFundi est un projet Wiki in Africa, destiné à aider Wikipédia. La plateforme WikiFundi a été imaginée par Florence Devouard et Isla Haddow-Flood dans le cadre du mouvement WikiAfrica. Le logiciel est réalisé en collaboration avec Kiwix. WikiFundi est financé par la Fondation Orange et la  Wikimedia Foundation. WikiFundi et sa documentation sont publiés sous la licence Creative Commons CC-BY-SA 4.0.

**Comment by rgaudin** [comment]
Added as a single-image in branding CSS.
![screen shot 2018-08-31 at 11 50 38 am](https://user-images.githubusercontent.com/57929/44910957-94ab3700-ad14-11e8-8d96-d17796abac92.png)
