### ISSUE TITLE
Inadequate render on small screen:2

### ISSUE THREAD

**Issue by michaelgraaf** [openzim/wikifundi#8]
In testing web page render on a different Samsung Android than in previous issue - with a smaller screen, no buttons were displayed at all, although clicking randomly in the blue box I managed to trigger one of them.

Solution could be rescaling and forcing landscape view as suggested in previous issue.

![20170427_061136](https://cloud.githubusercontent.com/assets/28103242/25486999/3684b216-2b63-11e7-9043-50d51094dab4.jpg)

**Comment by kelson42** [comment]
Thx for the report, maybe @Anthere can do something, I do not have developed that page.
