### ISSUE TITLE
Langage on the welcome screen

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#80]
On the main screen, the two boxes related to the WikiFundi have a quick description in French and English. But since the big buttons both says "CREER", I believe the difference between the two is not obvious. Please change the French text from "Environnement qui vous permet de créer des articles Wikipedia hors-ligne" to "Environnement qui vous permet de créer des articles Wikipedia hors-ligne (en français)"
and the English text from "Offline editable environment ... editing Wikipedia online" to "Offline editable environment ... editing Wikipedia online (in English)"

**Comment by kelson42** [comment]
@rgaudin (1) Do we have a translation bug here re? (2) Can you update the text like @Anthere ask for in Kiwix-plug installer?

**Comment by rgaudin** [comment]
Yes, it comes from our confit file.

**Comment by kelson42** [comment]
Fixed

**Comment by rgaudin** [comment]
Fixed in pibox.
