### ISSUE TITLE
Welcome screen: Access to resources

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#81]
On the main screen, the access to WikiFundi resources is very confusing for the users atm. 

1) The folder is a black folder (please change it to WikiFundi icon. probably the easiest and quickest way...).
 
2) the name of the folder is "Manage Edupi". This is mysterious as there is nothing related to management in that folder and the name is in English in both the French and English environnement. Can this be changed to another clearer name ? Such as "Resources Edupi" in English and "Ressources Edupi" in French ? 

3) the text below is currently "content management application". Which is actually... well... true perhaps but only fixed resources in there... how would users *guess* that they are simply ressources in there ?
What about changing the text "content management application" to a vaguer term, such as "resources" or "educational resources" or "educational content" ? Is that possible ?

**Comment by kelson42** [comment]
@Anthere For (1), We have already the logo in top left and for the two WikiFundi wikis... for sure adding a new WikiFundi logo as resources icon won't help to identify things for the users (3 times the same icon).
@rgaudin Can we custom the points (2) and (3) with CSS? I would then do it if "yes".

**Comment by rgaudin** [comment]
Perhaps but this remark is true for everybody : current text is not helpful.
We can reword it so it’s clearer but it will be kept general (no «
educational ») and maybe customized through CSS.

**Comment by rgaudin** [comment]
Fixed in pibox
![screen shot 2018-08-28 at 12 10 05 pm](https://user-images.githubusercontent.com/57929/44722922-210fec80-aabe-11e8-8aba-748b0d17cc59.png)
