### ISSUE TITLE
Dossier "ressources" sur la page d'accueil

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#83]
Actuellement dossier noir.

TODO : pour le deuxième item (ressources) virer simplement le dossier noir (ne pas mettre de logo... comme pour le premier item (accès à WikiFundi).

**Comment by kelson42** [comment]
The bug has been fixed and will be available in next images. You can already see the fix here (in EDUPI image) http://edupi-fr.demo.plug.kiwix.org/fr/
