### ISSUE TITLE
Navigation issues when going on the resources folder (wrong back home button)

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#85]
Quand on part se balader dans les ressources (par exemple, dans Vikidia) et qu'on clique sur le bouton maison en haut à gauche... le retour ne se fait pas sur le hotspot WikiFundi, mais sur kiwix.wikifundi.hotspot. Qui se présente visuellement assez différemment de la vraie page d'accueil  
![wikifundi ss 15](https://user-images.githubusercontent.com/19579170/45371543-2bb4a080-b5eb-11e8-9fdb-ebbf6e4f9690.jpeg)
![wikifundi ss 14](https://user-images.githubusercontent.com/19579170/45371544-2c4d3700-b5eb-11e8-8b1c-2d77d7ae652a.jpeg)

TODO : rediriger vers la bonne page d'accueil

**Comment by kelson42** [comment]
@Anthere Oui, on va configure Kiwix Hotspot de cette manière, voir https://framagit.org/ideascube/pibox-installer/issues/236

**Comment by rgaudin** [comment]
Done.
