### ISSUE TITLE
Référence intempestive à Popo...

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#86]
J'ai eu l'idée de cliquer sur l'icone Wikipedia. Tout marche bien, mais... bizarrement, il y a une référence à Popolechien en haut de l'écran à gauche...
Pour le Wiktionnaire, on voit apparaître référence à Stéphane. Et pour WikiMed, DocJames. Cest déjà plus raisonnable:) Mais « popo le chien », ça fait pas très pro...

Ce n'est pas un bug... plutôt un enhancement. 
![wikifundi ss 16](https://user-images.githubusercontent.com/19579170/45371955-10966080-b5ec-11e8-81a3-42b6d1b55efd.jpeg)

Todo : si la référence à Popo peut disparaître... c'est un peu confusionnant...

**Comment by kelson42** [comment]
Nous faison face ici à une limitation de Parsoid et je n'ai pas de workaround en tête suffisement propre... Je ferai les références au bug upstream plus tard... mais rien que nous pouvons faire pour le moment.

**Comment by Anthere** [comment]
Ca n'a rien de dramatique. Je pense que c'est juste un élément à lister dans vos améliorations générales futures (je sais, j'aime gratouiller)

**Comment by kelson42** [comment]
This bug is tracked here https://github.com/openzim/mwoffliner/issues/253
