### ISSUE TITLE
Visuel licence manquant dans l'outil WikiFundi proprement dit

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#87]
TODO : Bas d'écran, il manque un visuel (c'est la licence CC BY SA 3.0)
A priori, le visuel n'apparait pas car il est linké en ligne. Il est resté en "dur" au lieu d'être passé en local.
![wikifundi ss 18](https://user-images.githubusercontent.com/19579170/45372055-4c312a80-b5ec-11e8-9589-122c71302c95.jpeg)

D'ailleurs... pourquoi 3.0 ? Ca devrait pas être la 4.0 ?

**Comment by Anthere** [comment]
C'est couillon, on a marqué partout que l'outil était 4.0 :)))
bon, ben tant pis

**Comment by kelson42** [comment]
@Anthere In the last demo, I can not reproduce the problème. Everything seems to be OK with the logo http://fr.wikifundi.edupi-fr.demo.plug.kiwix.org/wiki/Accueil. Regarding the link, I have fixed it, it will be available in next image.
