### ISSUE TITLE
Mettre les "modifications récentes" à zéro avant publication finale

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#88]
Juste avant d'emballer le tout... il faudrait que les modifications récentes sur la page d'accueil soient vides au lieu de montrer plein de résidus d'import...

Ce serait plus propre. Pas dramatique si pas fait. Mais pas très pro.

**Comment by kelson42** [comment]
This topic has been discussed here too https://github.com/openzim/wikifundi/issues/89#issuecomment-421279756

**Comment by kelson42** [comment]
There is nothing more we can do here.

**Comment by kelson42** [comment]
@florentk Je viens de télécharger https://download.openzim.org/wikifundi/2.0/mediawiki_data_fr_2018-09.tar.bz2. J'ai ouvert la base sqlite et la table `recentchanges` n'est pas vide. Elle se doit de l'être pour résoudre ce pb. Cela semble faisable non?

**Comment by kelson42** [comment]
@florentk Elle n'est pas vide dans le dump et comme le dump n'est pas fait au milieu d'une migration partielle, on dirait bien qu'il y a un probleme.

**Comment by florentk** [comment]
@kelson42 je viens d'ajouter une instruction pour vider la table après une migration, à voir si ça marche
