### ISSUE TITLE
FR and EN Content is outdated 

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#89]
On the French version, the content archive is from the 8th of July. 
On the English version, the content archive is from the 9th of July.
However, corrections were done after those, since the beta version was released for Wikimania. 
See for example https://en.wikipedia.org/w/index.php?title=Wikipedia%3AWikiProject_WikiFundi_Content%2FMain_Page&type=revision&diff=849727800&oldid=849181745
On the EN current software, those two links are broken as it is still the old version. 
Some modifications were done yesterday to clarify the connexion issue.
Also just noted issues with some [[Help:]] links. Now fixed.

---> FRESH new content archives should be pulled in.

**Comment by florentk** [comment]
On http://wikifundi-en.openzim.org/wiki/Main_Page , the page is updated with the good link. I don't understand.

**Comment by kelson42** [comment]
@florentk I think there is nothing for you do to... we just need to make a new exported tarball of the wiki. @rgaudin will do that next week.

**Comment by rgaudin** [comment]
Well I'm not aware of the process so @florentk is there anything beyond just calling /export_data.php and downloading the file?

@Anthere, don't you want to _clean-up_ the import history in the home page first? Appears only on the French version though…

**Comment by florentk** [comment]
@rgaudin nothing else to do, just calling /export_data.php and downloading the file. The best is do the sunday night, to get a clean full mirroring

**Comment by rgaudin** [comment]
OK perfect ! 🙇

**Comment by kelson42** [comment]
Want to put an emphasis on the nice documentation https://github.com/openzim/wikifundi/blob/master/README.md :)

**Comment by rgaudin** [comment]
Where do you think I got the `export_data.php` part from ? 😁

**Comment by Anthere** [comment]
@Anthere, don't you want to clean-up the import history in the home page first? Appears only on the French version though…

> the import history should be cleaned. But this is not I who can do that :)

**Comment by rgaudin** [comment]
@florentk ?

**Comment by florentk** [comment]
@rgaudin This is because in FR version, it show the Botimport modifications, no in EN version. I don't no why

**Comment by florentk** [comment]
@Anthere when you go in this page http://wikifundi-fr.openzim.org/wiki/Sp%C3%A9cial:Modifications_r%C3%A9centes ,  nothing is show
Then, we have a problem with the "Accueil" page ?

**Comment by Anthere** [comment]
Florent, je ne sais pas trop quoi te dire. C'est simplement que lors de la création de l'image, il faut que le log des modifications récentes soit mis à zéro...

**Comment by florentk** [comment]
@Anthere  Mais les log de modifications sont bien remis à zéro, se qu'on voit sur la version FR (et pas sur la EN) c'est le log de la création des pages, qui lui ne peut pas être remis à zéro, puisque la page existe. Du coup le problème n'est pas de vider le log de modification, mais de ne pas afficher le log de création.

**Comment by rgaudin** [comment]
Pour info, j'ai refais un dump FR et EN hier et c'est avec ceux-ci que je vais refaire une image wikifundi. Le log est présent sur le FR…
