### ISSUE TITLE
No autodisplay on Linux & some Androids

### ISSUE THREAD

**Issue by michaelgraaf** [openzim/wikifundi#9]
In testing WF with groups of people, all users of Ubuntu and some of Android, didn't experience anything on joining the WF hotspot.

I later tested on an Ubuntu machine, the suggestion that one entered http://kiwix in a browser. 
Unsuccessful. 

As I don't have an Android which fails to display, I couldn't test the above URL.

**Comment by kelson42** [comment]
AFAIK all of this is client device (OS) specific. I'm not aware about anything I can do to help regarding this.

**Comment by kelson42** [comment]
We have fully changed the backend software, so I suspect this bug is outdated.
