### ISSUE TITLE
Liens cassés du fait d'un nommage d'espace erroné

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#91]
Dans l'outil, il y a un espace "Wikipedia:" dans la version EN et un espace "Wikipédia:" dans la version FR

Dans la version FR min, les deux espaces sont nommés "Wikipédia:". Donc sur WikiFundi FR... ça marche. Sur WikiFundi EN... ça ne marche pas du tout puisque les pages sont toutes nommées Wikipédia:XXX alors que les liens internes dans l'application pointent vers Wikipedia:XXX
Donc le système essaye de sortir de WikiFundi pour se connecter en ligne au vrai wikipedia...

J'imagine que le problème doit être l'opposé dans la version EN min (et max), à savoir que les deux espaces de noms doivent être Wikipedia:XXX alors que la version en français doit être Wikipédia:XXX. Bien sûr je n'ai pas vérifié cela puisque je n'ai pas la version EN min. Mais la logique voudrait qu'on retrouve en miroir le problème sur l'autre version linguistique.

Est-ce que je suis claire ?

**Comment by kelson42** [comment]
@florentk 
The namespace is properly site on "fr" indeed https://github.com/openzim/wikifundi/blob/master/wikifundi-fr/config/mediawiki/LocalSettings.custom.php#L19

But I see nothing similar on "en" !?

**Comment by kelson42** [comment]
@Anthere This problem is really old, this should really have been discovered earlier.

**Comment by Anthere** [comment]
Yeah. It should. I agree. I am very perplex I missed that.

**Comment by florentk** [comment]
@kelson42 I don't put namespace in EN version because I use the default one, it does not seem to be a problem on mirror. On other hand, article on wikipedia site, links can be broken, but in mirroring process, it seem that good namespace is take into account. We can put the namespace in file config, but I think that will change nothing

**Comment by kelson42** [comment]
@Anthere Tu nous donnes un exemple concret de lien cassé sur http://wikifundi-en.openzim.org/ stp?

**Comment by kelson42** [comment]
Après avoir discuté avec @Anthere visibleemnt tout est ok sur wikifundi-en.openzim.org, mais pas sur le plug.

**Comment by Anthere** [comment]
Note je suis dans le train. Deux jours sur Paris. Sur mon téléphone. Pas de plug sous la main. Et telephone qui bug a fond (j ai tenté de le noyer dans les toilettes. Il a pas aimé)
De retour vendredi vers 18h. Je vous enverrais des url d exemples. 

Mais en gros
Lors ce que je suis sur le Plug en interface française
Et que j’accède à wikifundi en anglais
Toutes les pages de type Wikipedia:
Se retrouve transformer en Wikipédia:
Donc tous les liens Interne dans les pages wiki de type Wikipedia:  cassé

**Comment by Anthere** [comment]
La plupart de ces pages sont appelees depuis la page wiki nommee Welcome. Acessible depuis le menu

**Comment by Anthere** [comment]
http://wikifundi-en.openzim.org/wiki/WikiFundi:Welcome

Exemple

http://wikifundi-en.openzim.org/wiki/Wikipedia:Identifying_reliable_sources

Mais sur le plug...

**Comment by florentk** [comment]
Ce problème me dit vaguement quelque chose, mais les vacances sont passés par là xD. Si mes souvenirs sont bon, j'avais dû justement enlevé  "l'extra namespace" "Wikipedia" de la configuration EN pour éviter ce genre de lien cassé. Après je me rappel plus pourquoi ça pose problème en anglais et pas en français. La question est : la fichier de config sur le "plug" est-il le même que sur wikifundi-en.openzim.org ?

**Comment by rgaudin** [comment]
C'est bon, j'ai trouvé le coupable !

C'est dans le [LocalSettings.php](https://github.com/openzim/mediawiki-docker/blob/master/config/mediawiki/LocalSettings.php#L358) (la config de base MW que l'on importe).

@florentk l'avait [modifié le 6 juillet](https://github.com/openzim/mediawiki-docker/commit/6a22d3a98d6648e2e9625963b01395b511d03912#diff-be8c949cdc0b7615959e4fa82c4ce372) mais c'est passé entre les mailles de mon filet… 

@kelson42 j'anticipe ta question : ce fichier est dans le docker ; il ne fait pas partie des tarballs.
Je vais récupérer la nouvelle version du fichier mais @florentk, ce serait bien je pense de mettre le NS EN aussi dans le config du tarball, pour plus de clareté.

Testé sur la démo: http://en.wikifundi.wikifundi-fr.demo.hotspot.kiwix.org/wiki/Wikipedia:Identifying_reliable_sources
