### ISSUE TITLE
First access to the tool should be "not logged" user mode

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#92]
Recent change in behavior. Previously, the first access to the tool was in the mode "not logged".
In last version, the first access is by default with a user connected to the admin account. 
Please rather make it "unlogged" for first access

**Comment by kelson42** [comment]
@Anthere If you are logged, then that probably means you have logged in... I can not figure out how the software could consider you logged without.

**Comment by Anthere** [comment]
seriously not... 
I wiped the SD card from anything that was on it.
Then I flashed it
Then I put it into the raspberry. 
Then connected to WikiFundi
Then opened a browser window, typed wikifundi.hotspot
Then clicked on the WikiFundi app icon (in English first)
And there you go... I get on the main page and I was logged as admin. 

Of course, to test... I logged out, went online, came back to wikifundi wifi, launched again wikifundi, clicked on the app; and NOW, I was not logged.

But the first time I accessed the application... I was logged in by default...

I know... very weird

**Comment by rgaudin** [comment]
@Anthere can you test from a different device so we can safely close this ticket?

**Comment by Anthere** [comment]
Renaud, I will try. 
But in any cases, I need a brand new image. I will wipe entirely the SD card again, flash it from new. Don't you think it will be enough to check if that issue is gone ? I can first check that. 
Then try it on a different raspberry. I have 3 left at home normally.

**Comment by rgaudin** [comment]
I meant a different device to access the Hotspot from ; like another
computer or phone.

**Comment by Anthere** [comment]
Ahhhh. Yes. at home... 4 laptops... 4 computers... 4 phones...
Yes will do.

**Comment by Anthere** [comment]
Testé et pas reproduit. Je vais clôturer en supposant avoir eu un moment d'égarement. Hop
