### ISSUE TITLE
Latex not working on the plug...

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#93]
Seen in the French version, in the sandbox page.

http://fr.wikifundi.edupi-fr.demo.plug.kiwix.org/wiki/Aide:Bac_%C3%A0_sable#Les_bo.C3.AEtes_d.C3.A9roulantes

![latex bug](https://user-images.githubusercontent.com/19579170/46375462-c9a00600-c693-11e8-80a1-b02fc563cf2b.jpeg)

Note: it works on the WikiFundi demo site http://wikifundi-fr.openzim.org/wiki/Aide:Bac_%C3%A0_sable#Les_bo.C3.AEtes_d.C3.A9roulantes

**Comment by kelson42** [comment]
@rgaudin Latex est visiblement pas installé correctement.

**Comment by rgaudin** [comment]
Oui, apparement MW est configuré pour utiliser l'API en ligne de la fondation… malgré les paltanqués de paquets LateX installés.
C'est le cas aussi bien sur le mirroir Openzim que donc dans la conf du plug… @florentk, est-ce normal ? un oubli ?

`https://wikimedia.org/api/rest_v1/media/math/render/svg/8e0608819fb1044b33bc4ca23b1b7b5f23e80517`

**Comment by kelson42** [comment]
@florentk Here is the related documentation to install latex https://www.mediawiki.org/wiki/MediaWiki_and_LaTeX_on_a_host_with_shell_access
@rgaudin Be ready to have hundreds of additional MB needed by Latex :(

**Comment by kelson42** [comment]
@florentk Would that be possible for you to fix this pb? In fact this is a blocker for the final release.

**Comment by florentk** [comment]
@rgaudin we should use mathoid/restbase : https://www.mediawiki.org/wiki/Extension:Math/Restbase
This allow to add a new rest API service used by Math extension.
An other solution is to not use Math extension and use mathtex.cgi : https://www.mediawiki.org/wiki/MediaWiki_and_LaTeX_on_a_host_with_shell_access

**Comment by rgaudin** [comment]
OK this sounds complicated :)

I am unable to respond regarding the `math`/`m`/`ma` tags but @kelson42 or @Anthere might…

**Comment by Anthere** [comment]
I do not have any specific insight on this :( Sorry. @kelson42 ?

**Comment by florentk** [comment]
je n'arrive pas à configurer l'extension Math pour le forcer à utiliser Texvc :( La, je suis bloqué. Peut-être se résoudre à utiliser mathoid ...

**Comment by kelson42** [comment]
@florentk Je vais regarder, mais la dernière fois que j'ai configuré cela c'était beaucoup plus simple.

**Comment by kelson42** [comment]
@florentk Je crois que j'ai enfin réussi à corriger le pb. Regarde  https://github.com/openzim/mediawiki-docker/commit/bd70b59d1382a6572edae2a456a2827dc5667a3d et https://github.com/openzim/mediawiki-docker/commit/7153b4cc3f7da9189653ef0c003b2eca570308ba. Merci si tu peux relancer manuellement la mise à jours des sites de demos.
@rgaudin Dès que tout est en place au niveau de Wikifundi, il faudra refaire un export (jette un coup d'oeil aux diffs pour ne rien oublier).

**Comment by rgaudin** [comment]
Excellent ! J'ai ajusté le setup dans KH ; je vais relancer un master.

Faites moi signe lorsque je peux refaire un export.
