### ISSUE TITLE
Display issue on main page of software in French

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#94]
the display on the French speaking version is broken. It looks as if the content of the central part of mediawiki was restricted to a max length. This is visible here : http://fr.wikifundi.wikifundi-fr.demo.hotspot.kiwix.org/wiki/Accueil and in attached file. 
There is no reason to restrict visibility and none of the other pages of the software do that; It was not the case before (results from the work on the log probably)
![main page](https://user-images.githubusercontent.com/19579170/47624300-603cd700-db1b-11e8-9294-eb6a4198021b.jpeg)

**Comment by kelson42** [comment]
So far I can see, this displays what is defined in the source of the page. If this is a bug, it has been there from the beginning. The width of the boxes may become larger if more content is inside.

**Comment by rgaudin** [comment]
As @kelson42 said, the problem lies in the `Accueil` WikiCode:

```
{| style="width:690px; border:none; background:none;"
| style="width:600px; text-align:center; white-space:nowrap; color:#000;" |
[[File:WikiFundi logo.png|300px]]
<div style="font-size:162%; border:none; margin:0; padding:.1em; color:#000;">Bienvenue sur WikiFundi !!</div>
|}
```
Specifying a fixed width of `690` and `600` for those table elements make them… fixed. One mobile, you get the opposite of the screenshot: top part is smaller than the latter as the table would be larger than the screen.

**Comment by Anthere** [comment]
fixed somehow
