### ISSUE TITLE
Log on main page of French version is New Pages instead of Recent Modifications

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#95]
Title says it all. 
It should be RM. It was RM before. Now it is NP.

(the previous bug resulting in bot import being logged has been correctly fixed)

**Comment by kelson42** [comment]
Not sure to fully understand what is wrong here as I lack the step-by-step procedure... But I do not remember that at some point we should automatically redirect to the recent changes after login on. To the contrary, I remember that - and this is also logic - we land to the welcome page.

**Comment by rgaudin** [comment]
This is all in the `Accueil` WikiCode.

Currently, the page says that it will display New Pages Modifications which it is:

```
{{Méta cadre
 | titre   = <b><center>Dernières pages créées</center></b>
 | lien    =
 | contenu =

{{Spécial:NewPages}}
```

What you want is to display Recent Changes:

```
{Méta cadre
 | titre   = <b><center>Dernières modifications</center></b>
 | lien    =
 | contenu =

{{Spécial:RecentChanges}}
```

**Comment by Anthere** [comment]
Résolu. Merci
